import type { ComprehensionItem, SpeakingPrompt, WritingPrompt } from '@/types';
import { slugify, uid } from '../storage';

export function buildListening(): ComprehensionItem[] {
  const items: ComprehensionItem[] = [
    {
      id: uid('ls'),
      kind: 'listening',
      level: 'A2',
      title: 'Der Anruf bei der Firma',
      category: 'Work',
      useSpeech: true,
      text: 'Guten Tag, IT-Service Müller, Sie sprechen mit Frau Schmidt. Ich rufe an, weil ich mich um den Ausbildungsplatz bewerben möchte. Können Sie mir sagen, bis wann ich meine Bewerbung schicken kann? – Ja, gern. Die Bewerbungsfrist endet am 15. September. Bitte schicken Sie Ihre Unterlagen per E-Mail an bewerbung@it-mueller.de. Sie können auch gern anrufen, wenn Sie Fragen haben. – Vielen Dank, das ist sehr nett. Ich schicke meine Unterlagen heute noch. – Sehr gut. Auf Wiederhören! – Auf Wiederhören!',
      vocab: [
        { de: 'die Bewerbungsfrist', en: 'application deadline' },
        { de: 'die Unterlagen', en: 'documents' },
        { de: 'per E-Mail schicken', en: 'to send by email' },
        { de: 'der Ausbildungsplatz', en: 'training place' },
      ],
      questions: [
        { id: uid('q'), prompt: 'Wer spricht am Telefon?', type: 'mcq', options: ['Herr Müller', 'Frau Schmidt', 'Der Chef'], answer: 'Frau Schmidt', explanation: 'Sie spricht mit Frau Schmidt.' },
        { id: uid('q'), prompt: 'Warum ruft die Person an?', type: 'mcq', options: ['Sie will ein Produkt kaufen.', 'Sie will sich bewerben.', 'Sie will kündigen.'], answer: 'Sie will sich bewerben.', explanation: 'Sie möchte sich um den Ausbildungsplatz bewerben.' },
        { id: uid('q'), prompt: 'Bis wann muss die Bewerbung geschickt werden?', type: 'mcq', options: ['15. August', '15. September', '1. Oktober'], answer: '15. September', explanation: 'Die Bewerbungsfrist endet am 15. September.' },
        { id: uid('q'), prompt: 'Wohin soll die Bewerbung geschickt werden?', type: 'mcq', options: ['per Post', 'per E-Mail', 'persönlich'], answer: 'per E-Mail', explanation: 'per E-Mail an bewerbung@it-mueller.de.' },
      ],
      durationMinutes: 5,
    },
    {
      id: uid('ls'),
      kind: 'listening',
      level: 'A2',
      title: 'Das Vorstellungsgespräch',
      category: 'Work',
      useSpeech: true,
      text: 'Guten Morgen, Frau Yilmaz. Schön, dass Sie da sind. Ich habe mir Ihre Bewerbung angesehen und bin sehr beeindruckt. Sie haben bereits Erfahrung mit JavaScript und arbeiten gern im Team. Können Sie mir erzählen, warum Sie Informatiker werden möchten? – Ja, gern. Ich interessiere mich schon lange für Software und möchte meine Ideen in echten Projekten umsetzen. – Sehr gut. Und wann können Sie anfangen? – Ich könnte im September beginnen, direkt nach meiner Prüfung. – Das passt perfekt. Wir melden uns nächste Woche bei Ihnen. Vielen Dank für das Gespräch!',
      vocab: [
        { de: 'das Vorstellungsgespräch', en: 'job interview' },
        { de: 'beeindruckt', en: 'impressed' },
        { de: 'umsetzen', en: 'to implement' },
        { de: 'anfangen', en: 'to start' },
      ],
      questions: [
        { id: uid('q'), prompt: 'Warum ist der Gesprächspartner beeindruckt?', type: 'mcq', options: ['Wegen der Bewerbung', 'Wegen der Erfahrung mit JavaScript', 'Wegen der Kleidung'], answer: 'Wegen der Erfahrung mit JavaScript', explanation: 'Er ist beeindruckt, weil sie Erfahrung mit JavaScript hat.' },
        { id: uid('q'), prompt: 'Wann kann Frau Yilmaz anfangen?', type: 'mcq', options: ['Im August', 'Im September', 'Im Oktober'], answer: 'Im September', explanation: 'Nach ihrer Prüfung, im September.' },
        { id: uid('q'), prompt: 'Wann meldet sich die Firma?', type: 'mcq', options: ['Morgen', 'Nächste Woche', 'Nächsten Monat'], answer: 'Nächste Woche', explanation: 'Wir melden uns nächste Woche.' },
      ],
      durationMinutes: 5,
    },
    {
      id: uid('ls'),
      kind: 'listening',
      level: 'B1',
      title: 'Nachrichten: IT-Branche',
      category: 'Technology',
      useSpeech: true,
      text: 'Die IT-Branche in Deutschland wächst weiter. Viele Firmen suchen dringend Fachkräfte, besonders im Bereich Cybersicherheit und Softwareentwicklung. Ausbildungsplätze für Fachinformatiker sind stark nachgefragt. Die Industrie- und Handelskammer meldet, dass in diesem Jahr zehn Prozent mehr Azubis eingestellt werden als im Vorjahr. Experten empfehlen jungen Menschen, sich frühzeitig zu bewerben, da die besten Plätze schnell vergeben sind. Auch die Gehälter steigen leicht an, besonders in Großstädten wie München und Berlin.',
      vocab: [
        { de: 'die Fachkräfte', en: 'specialists' },
        { de: 'nachgefragt', en: 'in demand' },
        { de: 'die Industrie- und Handelskammer (IHK)', en: 'Chamber of Commerce' },
        { de: 'vergeben', en: 'allocated/assigned' },
      ],
      questions: [
        { id: uid('q'), prompt: 'In welchen Bereichen sucht die Branche besonders Fachkräfte?', type: 'mcq', options: ['Marketing und Verkauf', 'Cybersicherheit und Softwareentwicklung', 'Logistik und Transport'], answer: 'Cybersicherheit und Softwareentwicklung', explanation: 'besonders im Bereich Cybersicherheit und Softwareentwicklung.' },
        { id: uid('q'), prompt: 'Wie viel mehr Azubis werden dieses Jahr eingestellt?', type: 'mcq', options: ['Fünf Prozent', 'Zehn Prozent', 'Fünfzehn Prozent'], answer: 'Zehn Prozent', explanation: 'zehn Prozent mehr Azubis als im Vorjahr.' },
        { id: uid('q'), prompt: 'Was empfehlen Experten?', type: 'mcq', options: ['Später zu bewerben', 'Sich frühzeitig zu bewerben', 'Nicht zu bewerben'], answer: 'Sich frühzeitig zu bewerben', explanation: 'die besten Plätze sind schnell vergeben.' },
        { id: uid('q'), prompt: 'Wo steigen die Gehälter besonders?', type: 'mcq', options: ['In kleinen Dörfern', 'In Großstädten', 'Im Ausland'], answer: 'In Großstädten', explanation: 'besonders in Großstädten wie München und Berlin.' },
      ],
      durationMinutes: 6,
    },
    {
      id: uid('ls'),
      kind: 'listening',
      level: 'A2',
      title: 'Im Deutschkurs',
      category: 'Study',
      useSpeech: true,
      text: 'Hallo zusammen! Willkommen im Deutschkurs B1. Ich bin Ihre Lehrerin, Frau Weber. Unser Kurs findet dreimal pro Woche statt: montags, mittwochs und freitags von 18 bis 20 Uhr. Nächste Woche beginnen wir mit dem Thema Grammatik und danach machen wir viele Übungen zum Wortschatz. Am Ende des Kurses können Sie eine Prüfung machen. Wenn Sie Fragen haben, sprechen Sie mich einfach nach dem Unterricht an.',
      vocab: [
        { de: 'stattfinden', en: 'to take place' },
        { de: 'der Unterricht', en: 'lesson' },
        { de: 'ansprechen', en: 'to address' },
      ],
      questions: [
        { id: uid('q'), prompt: 'Wie oft findet der Kurs statt?', type: 'mcq', options: ['Zweimal pro Woche', 'Dreimal pro Woche', 'Viermal pro Woche'], answer: 'Dreimal pro Woche', explanation: 'montags, mittwochs und freitags.' },
        { id: uid('q'), prompt: 'Um wie viel Uhr beginnt der Kurs?', type: 'mcq', options: ['18 Uhr', '19 Uhr', '20 Uhr'], answer: '18 Uhr', explanation: 'von 18 bis 20 Uhr.' },
        { id: uid('q'), prompt: 'Was ist das nächste Thema?', type: 'mcq', options: ['Wortschatz', 'Grammatik', 'Lesen'], answer: 'Grammatik', explanation: 'Nächste Woche beginnen wir mit Grammatik.' },
      ],
      durationMinutes: 4,
    },
  ];
  return items.map((item) => ({ ...item, id: `listen-${slugify(item.title)}` }));
}

export function buildReading(): ComprehensionItem[] {
  const items: ComprehensionItem[] = [
    {
      id: uid('rd'),
      kind: 'reading',
      level: 'A2',
      title: 'Ausbildungsplatz als Fachinformatiker',
      category: 'Job advertisements',
      text: 'Ausbildungsplatz 2026 — Fachinformatiker/in Anwendungsentwicklung\n\nDie Firma CodeHub GmbH in Hamburg sucht zum 1. August 2026 Auszubildende für den Beruf Fachinformatiker Anwendungsentwicklung. Du lernst bei uns, Software zu entwickeln, Datenbanken zu gestalten und mit modernen Technologien zu arbeiten. Voraussetzungen: guter Schulabschluss, Interesse an Technik und Logik, erste Erfahrungen mit Computern sind von Vorteil. Wir bieten ein freundliches Team, eine moderne Ausstattung und eine faire Ausbildungsvergütung. Bewirb dich bis zum 31. Mai 2026 mit Lebenslauf und Anschreiben per E-Mail an jobs@codehub.de.',
      vocab: [
        { de: 'der Auszubildende', en: 'trainee' },
        { de: 'die Voraussetzungen', en: 'requirements' },
        { de: 'von Vorteil', en: 'an advantage' },
        { de: 'die Ausbildungsvergütung', en: 'training allowance' },
      ],
      questions: [
        { id: uid('q'), prompt: 'Was sucht die Firma CodeHub?', type: 'mcq', options: ['Ein Produkt', 'Auszubildende', 'Neue Kunden'], answer: 'Auszubildende', explanation: 'sucht zum 1. August 2026 Auszubildende.' },
        { id: uid('q'), prompt: 'In welcher Stadt ist die Firma?', type: 'mcq', options: ['Berlin', 'München', 'Hamburg'], answer: 'Hamburg', explanation: 'in Hamburg.' },
        { id: uid('q'), prompt: 'Was sollst du mit der Bewerbung schicken?', type: 'mcq', options: ['Lebenslauf und Anschreiben', 'Nur Lebenslauf', 'Zeugnisse nur'], answer: 'Lebenslauf und Anschreiben', explanation: 'mit Lebenslauf und Anschreiben.' },
        { id: uid('q'), prompt: 'Bis wann soll man sich bewerben?', type: 'mcq', options: ['31. Mai', '1. August', '31. Juli'], answer: '31. Mai', explanation: 'Bewirb dich bis zum 31. Mai 2026.' },
      ],
      durationMinutes: 7,
    },
    {
      id: uid('rd'),
      kind: 'reading',
      level: 'B1',
      title: 'Leben und Arbeiten in Deutschland',
      category: 'German culture',
      text: 'In Deutschland beginnt das Arbeitsjahr offiziell mit der beruflichen Ausbildung, die meistens am 1. August oder 1. September startet. Das duale System ist weltweit bekannt: Die Azubis lernen sowohl im Betrieb als auch in der Berufsschule. Die Berufsschule findet ein bis zwei Tage pro Woche statt, den Rest der Woche arbeitet man im Betrieb und lernt praktisch. Am Ende der Ausbildung legt man eine Prüfung bei der Industrie- und Handelskammer (IHK) ab. Während der Ausbildung bekommt man ein Gehalt, die Ausbildungsvergütung. Nach erfolgreichem Abschluss hat man sehr gute Chancen, vom Betrieb übernommen zu werden.',
      vocab: [
        { de: 'das duale System', en: 'the dual system' },
        { de: 'die Berufsschule', en: 'vocational school' },
        { de: 'ablegen', en: 'to take (an exam)' },
        { de: 'übernehmen', en: 'to take on/hire' },
      ],
      questions: [
        { id: uid('q'), prompt: 'Wann startet die Ausbildung meistens?', type: 'mcq', options: ['Im Januar', 'Im August oder September', 'Im März'], answer: 'Im August oder September', explanation: 'meistens am 1. August oder 1. September.' },
        { id: uid('q'), prompt: 'Wo lernen die Azubis?', type: 'mcq', options: ['Nur im Betrieb', 'Nur in der Schule', 'Im Betrieb und in der Berufsschule'], answer: 'Im Betrieb und in der Berufsschule', explanation: 'Das ist das duale System.' },
        { id: uid('q'), prompt: 'Wo legt man die Prüfung ab?', type: 'mcq', options: ['Bei der IHK', 'In der Firma', 'In der Universität'], answer: 'Bei der IHK', explanation: 'eine Prüfung bei der Industrie- und Handelskammer.' },
        { id: uid('q'), prompt: 'Was passiert oft nach der Ausbildung?', type: 'mcq', options: ['Man muss gehen', 'Man wird übernommen', 'Man studiert sofort'], answer: 'Man wird übernommen', explanation: 'sehr gute Chancen, übernommen zu werden.' },
      ],
      durationMinutes: 8,
    },
    {
      id: uid('rd'),
      kind: 'reading',
      level: 'A2',
      title: 'Mein Tagesablauf',
      category: 'Daily life',
      text: 'Ich stehe jeden Morgen um 6 Uhr auf. Zuerst trinke ich einen Kaffee und esse ein Brötchen. Dann lerne ich eine Stunde Deutsch, denn die Prüfung kommt bald. Um 8 Uhr fahre ich zur Arbeit. Ich arbeite als Entwicklerpraktikant bei einem kleinen IT-Startup. Mittags esse ich mit meinen Kollegen in der Kantine. Nach der Arbeit gehe ich oft ins Fitnessstudio oder treffe mich mit Freunden. Abends wiederhole ich die Vokabeln und schaue eine deutsche Serie. Um 23 Uhr gehe ich schlafen.',
      vocab: [
        { de: 'der Tagesablauf', en: 'daily routine' },
        { de: 'aufstehen', en: 'to get up' },
        { de: 'das Fitnessstudio', en: 'gym' },
        { de: 'wiederholen', en: 'to review' },
      ],
      questions: [
        { id: uid('q'), prompt: 'Wann steht die Person auf?', type: 'mcq', options: ['Um 5 Uhr', 'Um 6 Uhr', 'Um 7 Uhr'], answer: 'Um 6 Uhr', explanation: 'Ich stehe um 6 Uhr auf.' },
        { id: uid('q'), prompt: 'Warum lernt die Person morgens Deutsch?', type: 'mcq', options: ['Weil es Spaß macht', 'Weil die Prüfung bald kommt', 'Weil der Kurs ist'], answer: 'Weil die Prüfung bald kommt', explanation: 'denn die Prüfung kommt bald.' },
        { id: uid('q'), prompt: 'Was macht die Person abends?', type: 'mcq', options: ['Arbeitet', 'Wiederholt Vokabeln', 'Schläft sofort'], answer: 'Wiederholt Vokabeln', explanation: 'Abends wiederhole ich die Vokabeln.' },
        { id: uid('q'), prompt: 'Wo arbeitet die Person?', type: 'mcq', options: ['Bei einem großen Konzern', 'Bei einem IT-Startup', 'In einer Schule'], answer: 'Bei einem IT-Startup', explanation: 'bei einem kleinen IT-Startup.' },
      ],
      durationMinutes: 6,
    },
    {
      id: uid('rd'),
      kind: 'reading',
      level: 'B1',
      title: 'Sicher im Netz: Tipps für Azubis',
      category: 'Technology',
      text: 'Cybersicherheit ist auch für Azubis wichtig. Hier sind drei Tipps: Erstens, verwende für jeden Dienst ein eigenes, starkes Passwort und nutze einen Passwortmanager. Zweitens, erkenne Phishing-E-Mails: Prüfe immer die Absenderadresse und klicke nicht auf unbekannte Links. Drittens, halte deine Software aktuell, denn Updates schließen Sicherheitslücken. Wenn du unsicher bist, frage deinen Ausbilder oder die IT-Abteilung. Ein sicherer Umgang mit Daten ist eine wichtige Fähigkeit für jeden IT-Beruf.',
      vocab: [
        { de: 'das Passwort', en: 'password' },
        { de: 'der Passwortmanager', en: 'password manager' },
        { de: 'die Sicherheitslücke', en: 'security gap' },
        { de: 'der Umgang', en: 'handling' },
      ],
      questions: [
        { id: uid('q'), prompt: 'Was sollst du für jeden Dienst verwenden?', type: 'mcq', options: ['Das gleiche Passwort', 'Ein eigenes starkes Passwort', 'Kein Passwort'], answer: 'Ein eigenes starkes Passwort', explanation: 'für jeden Dienst ein eigenes, starkes Passwort.' },
        { id: uid('q'), prompt: 'Wie erkennst du Phishing-E-Mails?', type: 'mcq', options: ['An der Länge', 'An der Absenderadresse', 'Am Thema'], answer: 'An der Absenderadresse', explanation: 'Prüfe immer die Absenderadresse.' },
        { id: uid('q'), prompt: 'Warum sind Updates wichtig?', type: 'mcq', options: ['Sie machen alles schneller', 'Sie schließen Sicherheitslücken', 'Sie löschen Daten'], answer: 'Sie schließen Sicherheitslücken', explanation: 'Updates schließen Sicherheitslücken.' },
        { id: uid('q'), prompt: 'Wen sollst du bei Unsicherheit fragen?', type: 'mcq', options: ['Deinen Ausbilder', 'Deine Freunde', 'Fremde im Internet'], answer: 'Deinen Ausbilder', explanation: 'frage deinen Ausbilder oder die IT-Abteilung.' },
      ],
      durationMinutes: 7,
    },
  ];
  return items.map((item) => ({ ...item, id: `read-${slugify(item.title)}` }));
}

export function buildWritingPrompts(): WritingPrompt[] {
  const items: WritingPrompt[] = [
    {
      id: uid('wp'),
      level: 'A2',
      title: 'E-Mail an den Deutschlehrer',
      situation: 'Du hast eine Frage zu den Hausaufgaben. Schreibe eine kurze, formelle E-Mail an deinen Lehrer.',
      task: 'Schreibe eine E-Mail an deinen Deutschlehrer, Herrn Klein. Erkläre, welches Thema du nicht verstehst, und frage, ob du die Aufgaben später abgeben kannst.',
      requirements: ['Anrede und Grußformel', 'Begründung, warum du schreibst', 'Eine konkrete Frage', 'Einfache Sätze'],
      minWords: 60,
      maxWords: 100,
      skillFocus: ['grammar', 'writing'],
    },
    {
      id: uid('wp'),
      level: 'B1',
      title: 'Informelle Nachricht an einen Freund',
      situation: 'Dein Freund Max hat dir geschrieben, dass er am Wochenende nach Berlin kommt.',
      task: 'Schreibe eine informelle Nachricht an Max. Begrüße ihn, schlage ein Treffen vor und erzähle, was du in Berlin zeigen kannst.',
      requirements: ['Informelle Anrede ("Hallo Max")', 'Vorschlag für ein Treffen', 'Zwei Aktivitäten', 'Frage am Ende'],
      minWords: 80,
      maxWords: 130,
      skillFocus: ['grammar', 'vocabulary'],
    },
    {
      id: uid('wp'),
      level: 'B1',
      title: 'Anschreiben für einen Ausbildungsplatz',
      situation: 'Du möchtest dich bei der Firma TechSolutions GmbH für eine Ausbildung als Fachinformatiker bewerben.',
      task: 'Schreibe ein Anschreiben. Stelle dich vor, erkläre dein Interesse an IT und begründe, warum du der richtige Kandidat bist.',
      requirements: ['Absender und Betreff', 'Formelle Anrede', 'Drei Absätze', 'Höflicher Schluss'],
      minWords: 120,
      maxWords: 180,
      skillFocus: ['grammar', 'writing', 'vocabulary'],
    },
    {
      id: uid('wp'),
      level: 'B1',
      title: 'Mein Weg nach Deutschland',
      situation: 'Du willst über deine Pläne für die Zukunft schreiben.',
      task: 'Schreibe einen Text über deine Pläne: Warum möchtest du eine Ausbildung in Deutschland machen? Was hast du schon dafür getan?',
      requirements: ['Vergangenheit und Zukunft', 'Begründungen mit "weil"', 'Persönliche Meinung'],
      minWords: 100,
      maxWords: 160,
      skillFocus: ['grammar', 'vocabulary'],
    },
    {
      id: uid('wp'),
      level: 'A2',
      title: 'Beschwerde-E-Mail',
      situation: 'Du hast online einen Laptop gekauft, aber er funktioniert nicht richtig.',
      task: 'Schreibe eine E-Mail an den Onlineshop. Beschreibe das Problem und sage, was du erwartest (z.B. Reparatur oder neues Gerät).',
      requirements: ['Betreff', 'Beschreibung des Problems', 'Was du erwartest', 'Höflicher Ton'],
      minWords: 70,
      maxWords: 120,
      skillFocus: ['grammar', 'writing'],
    },
    {
      id: uid('wp'),
      level: 'B1',
      title: 'Mein Lieblingsprogramm',
      situation: 'Du sollst über Technologie schreiben.',
      task: 'Beschreibe eine App oder ein Programm, das du oft benutzt. Was kann es? Warum magst du es? Würdest du es empfehlen?',
      requirements: ['Beschreibung der Funktionen', 'Begründung', 'Empfehlung'],
      minWords: 90,
      maxWords: 140,
      skillFocus: ['vocabulary', 'grammar'],
    },
  ];
  return items.map((item) => ({ ...item, id: `write-${slugify(item.title)}` }));
}

export function buildSpeakingPrompts(): SpeakingPrompt[] {
  const items: SpeakingPrompt[] = [
    {
      id: uid('sp'),
      level: 'A2',
      title: 'Selbstvorstellung',
      topic: 'Introduce yourself',
      situation: 'Stell dich vor einem neuen Team vor. Sage, wie du heißt, woher du kommst, was du machst und was dein Ziel ist.',
      questions: [
        'Wie heißt du und woher kommst du?',
        'Was machst du beruflich oder was lernst du?',
        'Warum möchtest du nach Deutschland?',
        'Was sind deine Hobbys?',
      ],
      durationMinutes: 5,
    },
    {
      id: uid('sp'),
      level: 'B1',
      title: 'Vorstellungsgespräch Simulation',
      topic: 'Job interview',
      situation: 'Dein Ausbilder stellt dir Fragen in einem Vorstellungsgespräch für einen IT-Ausbildungsplatz.',
      questions: [
        'Erzählen Sie etwas über sich. Wer sind Sie?',
        'Warum möchten Sie eine Ausbildung in der IT machen?',
        'Welche technischen Erfahrungen haben Sie schon?',
        'Was sind Ihre Stärken und Schwächen?',
        'Wo sehen Sie sich in fünf Jahren?',
        'Haben Sie Fragen an uns?',
      ],
      durationMinutes: 8,
    },
    {
      id: uid('sp'),
      level: 'A2',
      title: 'Alltagsgespräch: Wochenende',
      topic: 'Daily life',
      situation: 'Sprich mit einem Freund über dein Wochenende und deine Pläne.',
      questions: [
        'Was hast du am Wochenende gemacht?',
        'Was machst du gern in deiner Freizeit?',
        'Wie war dein Tag heute?',
      ],
      durationMinutes: 4,
    },
    {
      id: uid('sp'),
      level: 'B1',
      title: 'Mein Traumberuf',
      topic: 'Career',
      situation: 'Erkläre, welcher IT-Beruf dich interessiert und warum.',
      questions: [
        'Welchen Beruf möchtest du in Deutschland lernen?',
        'Warum interessierst du dich für diesen Beruf?',
        'Welche Aufgaben würdest du gern machen?',
        'Was macht diesen Beruf für dich besonders?',
      ],
      durationMinutes: 6,
    },
    {
      id: uid('sp'),
      level: 'B1',
      title: 'Eine Stadt in Deutschland',
      topic: 'Culture',
      situation: 'Beschreibe eine Stadt in Deutschland, die du besuchen oder in der du leben möchtest.',
      questions: [
        'Welche Stadt interessiert dich?',
        'Was weißt du über diese Stadt?',
        'Was möchtest du dort sehen oder erleben?',
        'Warum ist diese Stadt gut für eine Ausbildung?',
      ],
      durationMinutes: 6,
    },
    {
      id: uid('sp'),
      level: 'B1',
      title: 'Leben in Deutschland',
      topic: 'Integration',
      situation: 'Sprich über deine Erwartungen und Ängste an ein neues Leben in Deutschland.',
      questions: [
        'Was erwartest du von deinem Leben in Deutschland?',
        'Was könnte für dich schwierig sein?',
        'Wie möchtest du dich integrieren?',
        'Was möchtest du über die deutsche Kultur lernen?',
      ],
      durationMinutes: 6,
    },
  ];
  return items.map((item) => ({ ...item, id: `speak-${slugify(item.title)}` }));
}
